name: Deploy to AWS

on:
  push:
    branches:
      - telegram-mini-app

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Pull and Restart on AWS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /home/admin/Projects/stock101
            git pull
            sudo systemctl restart stock101-telegram.service
